SpartanRooms10-31-19/Controllers/BookingContainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SpartanRooms10_31_19.Models;
using SpartanRoomsData;
using SpartanRoomsData.Models;

namespace SpartanRooms10_31_19.Controllers
{
    public class BookingContainerController : Controller
    {
        private readonly DataContext _context;

        public BookingContainerController(DataContext context)
        {
            _context = context;
        }

        public IActionResult CalView()
        {
            return View();
        }

        // GET: BookingContainer
        public async Task<IActionResult> Index()
        {
            DisplayRoomsViewModel returnToView = new DisplayRoomsViewModel();
            returnToView.BookingContainerList = new List<BookingContainer>();
            returnToView.countOfRooms = new Dictionary<int, int>();

            returnToView.Rooms = new List<Room>();
            returnToView.initTimeArray();
            var bookingContainers = await _context.BookingContainers.ToListAsync();
            returnToView.Rooms = await _context.Rooms.ToListAsync();
            foreach(var booking in bookingContainers)
            {
                var result = (from a in _context.BookingContainers
                              where a.ID == booking.ID
                              select new BookingContainer { ID = a.ID, RoomID = a.RoomID, Reservations=a.Reservations, Room=a.Room, DateTime=a.DateTime }).ToList();

                if (result[0].Reservations.Count-1>= result[0].Room.Capacity)
                {
                    result[0].isFull = true;
                }

                returnToView.BookingContainerList.Add(result[0]);


                //Turns out I dont need to do this. 
                //" select new BookingContainer { ID = a.ID, RoomID = a.RoomID, Reservations=a.Reservations, Room=a.Room } finds all the related objects for me 0.0
                ////ADD ROOMS TO BOOKIINGCONTAINER
                ////add all returned booking containers into returnToViewList
                ////Should only be one though. booking.ID is unique primary key
                //foreach(var r in result)
                //{
                //    //finds all the Room objects with the same ID as r ( should only be 1 room obj)
                //    var rooms= (from a in _context.Rooms
                //                where a.ID == r.RoomID
                //                select new Room { ID = a.ID, RoomName =a.RoomName, Type=a.Type }).ToList();


                //    //var reservations = (from a in _context.Reservations
                //    //                    where a.)

                //    //should only run once since room.ID is unique
                //    foreach(var s in rooms)
                //    {
                //        //sets booking objects rooms to the related entries in database
                //        r.Room = s;
                //    }

                //    returnToView.Add(r);
                //}
                ////END OF ADD ROOMS TO BOOKING CONTAINER




                //var roomID = _context.BookingContainers.Include(i => i.RoomID).Where(r => r.ID == booking.ID);
                //booking.Room.ID= _context.BookingContainers.Find()
            }


            returnToView.BookingContainerList.Sort((x, y) => DateTime.Compare(x.DateTime, y.DateTime));

            var copyOfReturnToView = returnToView;
            copyOfReturnToView.BookingContainerList.Sort((x, y) => string.Compare(x.Room.RoomName.ToLower(), y.Room.RoomName.ToLower()));

            //string current="init";
            //string previous="init";
            //int count = 0;
            int[] countArray = new int[copyOfReturnToView.Rooms.Count];
            int countArrayIndex = 0;
            foreach(var item in returnToView.BookingContainerList)
            {
                countArrayIndex = 0;
                foreach (var room in copyOfReturnToView.Rooms)
                {
                    if (item.Room.ID == room.ID)
                    {
                        //copyOfReturnToView.BookingContainerList.Remove(item);
                        countArray[countArrayIndex]++;

                    }
                    countArrayIndex++;
                }

            }

            countArrayIndex = 0;

            foreach (var room in returnToView.Rooms)
            {
                returnToView.countOfRooms.Add(room.ID, countArray[countArrayIndex]);
                countArrayIndex++;
            }
            
            var dummy = 1;
            returnToView.alreadyRenderedRooms = new string[bookingContainers.Count];
            returnToView.alreadyCompletedRender = new List<string>();
            return View(returnToView);

        }

        // GET: BookingContainer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingContainer = await _context.BookingContainers
                .FirstOrDefaultAsync(m => m.ID == id);
            if (bookingContainer == null)
            {
                return NotFound();
            }

            return View(bookingContainer);
        }


        // GET: Reservations/Create
        public async Task<IActionResult> CreateReservation(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.BookingContainers
                .FirstOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }
            var students = _context.Students.ToList();

            var CreateReservationsViewModel = new CreateReservationViewModel();


            //foreach(var student in students)
            //{
            //    CreateReservationsViewModel.Students.Add(student);

            //}
            CreateReservationsViewModel.BookingContainer = booking;
            CreateReservationsViewModel.Students = students;

            return View(CreateReservationsViewModel);
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateReservation(int? id, CreateReservationViewModel viewModel)
        {

            if (id == null)
            {
                return NotFound();
            }

            BookingContainer bookingContainer = await _context.BookingContainers.FindAsync(id);
            if (bookingContainer == null)
            {
                return NotFound();
            }

            Reservation reservationContainer = new Reservation();
            //Student studentPostIform = values["Student"];
            if (ModelState.IsValid)
            {

                reservationContainer.Student = await _context.Students.FindAsync(viewModel.Student.ID);
                if (reservationContainer.Student == null)
                {
                    return NotFound();
                }
                bookingContainer.Reservations = new List<Reservation>();
                bookingContainer.Reservations.Add(reservationContainer);

                _context.Add(reservationContainer);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(bookingContainer);
        }




        // GET: BookingContainer/Create
        public IActionResult Create()
        {
            CreateBookingViewModel viewModel = new CreateBookingViewModel();
            viewModel.Rooms = _context.Rooms.ToList();

            viewModel.RoomIDs = viewModel.Rooms.ConvertAll(a=>
            {
                return new SelectListItem()
                {
                    Text = a.RoomName.ToString(),
                    Value = a.ID.ToString(),
                    Selected = false
                };
            }
                );


            //foreach(var room in viewModel.Rooms)
            //{
            //    viewModel.RoomIDs.Add(room.ID.ToSele)

            //}
            viewModel.RoomIDs.Sort((x, y) => string.Compare(x.Text, y.Text));
            return View(viewModel);
        }


        // POST: BookingContainer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookingViewModel viewModel, List<CreateBookingViewModel> viewModelList)
        {
            //[Bind("ID,DateTime,isFull")]
        BookingContainer bookingContainer= new BookingContainer();
            int bookingContainersSize = viewModel.PostedIDs.Count;
            BookingContainer[] bookingContainers = new BookingContainer[bookingContainersSize]; ;

            if (ModelState.IsValid)
            {
                int i = 0;
                foreach(var entry in viewModel.PostedIDs)
                {
                    bookingContainers[i] = new BookingContainer();
                    bookingContainers[i].DateTime = viewModel.BookingContainer.DateTime;
                    var ID = Convert.ToInt32(viewModel.PostedIDs[i]);
                    bookingContainers[i].Room = _context.Rooms.Find(ID);


                    Reservation initReservation = new Reservation();
                    initReservation.ReservationString = "Initialized";
                    bookingContainers[i].Reservations = new List<Reservation>();

SpartanRooms10-31-19/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SpartanRooms10_31_19.Models;

namespace SpartanRooms10_31_19.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SpartanRooms10-31-19/Views/Home/AltIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-left">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>*@


<style>
    .SpartanBody {
        background-image: url(https://www.rcm.it/wp-content/uploads/2019/09/pulire-scuola.jpg);
    }

    .SpartanNav {
        background-color: #f3cb7a;
        background-repeat: no-repeat;
        background-size: 70%;
        background-position: right;
    }
</style>

<body>
    <div style="margin-left:30%; float:left">
        <div style="position: relative; margin-left: -25%;width: 40%;">
            <form class="text-center border border-light p-5">

                <p class="h4 mb-4" style="color:white">Welcome To</p>
                <p style="margin-top: 5px;font-family:'Open Sans'; color:white; font-size: 35px"> Spartan Rooms</p>
                <p style="font-family:'High Tower Text'; color:white"> Reserve a Classroom!</p>
                <!-- Email -->
                <input type="email" id="defaultLoginFormEmail" class="form-control mb-4" placeholder="E-mail" style="border-radius: 35px">

                <!-- Password -->
                <input type="password" id="defaultLoginFormPassword" class="form-control mb-4" placeholder="Password" style="border-radius: 35px">

                <div class="d-flex justify-content-around">
                    <div>
                        <!-- Remember me -->
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                            <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>
                        </div>
                    </div>
                </div>

                <!-- Sign in button -->
                <button class="btn btn-info btn-block my-4" style="border-radius:35px" type="submit">Log in</button>

                <!-- Register -->
                <p>
                    Not a member?
                    <a href="">Register</a>
                </p>
            </form>
        </div>
    </div>

    <div class="SpartanBody" style=" margin-right:70%">

    </div>

</body>

SpartanRooms10-31-19/Views/Home/Index.cshtml
<style>
    .SpartanImage {

        background-image: url(https://www.rcm.it/wp-content/uploads/2019/09/pulire-scuola.jpg);
    }

    .SpartanLeftBackGroundColor{
        background-color: #f3cb7a;

    }

    .idk{
        background-repeat: no-repeat;
        background-size: 70%;
        background-position: right;
    }
    .fitPage{
        height:85vh
    }
    .fitTo100{
        height:100%
    }
</style>

<script>


</script>
    <div name="WrapperDiv" class="container-fluid fitPage" style="background-color: #f3cb7a" >
        <div class="flex-md-grow-0 container-fluid fitTo100">
            <div name="LoginContainer" class="col-md-10 container-fluid">
                <!--style="position: relative; margin-left: 90vh;width: 400px;"-->
                <form class="text-center p-5">

                    <p class="h4 mb-4">Welcome To</p>
                    <p> Spartan Rooms</p>
                    <p> Reserve a Classroom!</p>
                    <!-- Email -->
                    <input type="email" id="defaultLoginFormEmail" class="form-control mb-4" placeholder="E-mail">

                    <!-- Password -->
                    <input type="password" id="defaultLoginFormPassword" class="form-control mb-4" placeholder="Password">

                    <div class="d-flex justify-content-around" style="float:left">
                        <div>
                            <!-- Remember me -->
                            <div class="custom-control custom-checkbox" >
                                <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                                <label class="custom-control-label" for="defaultLoginFormRemember" >Remember me</label>
                            </div>
                        </div>
                    </div>

                    <!-- Sign in button -->
                    <button class="btn btn-info btn-block my-4" asp-area="" asp-controller="BookingContainer" asp-action="Index" style="border-radius:50px" type="submit">
                        @*<a class="nav-link text-dark" asp-area="" asp-controller="BookingContainer" asp-action="Index"></a>*@
                        Log in
                    </button>

                    <!-- Register -->
                    <p>
                        Not a member?
                        <a class="nav-link text-dark" asp-area="" asp-controller="BookingContainer" asp-action="Index">Register!</a>

                    </p>
                </form>
            </div>
        </div>
        @*<div name="roomImageDiv" style="width:70%; height:100%;float:right;">
            <div style="width:100%; height:100%;background-repeat:no-repeat;background-image: url(https://www.rcm.it/wp-content/uploads/2019/09/pulire-scuola.jpg);background-size:cover;display:inline-block;background-position: center center">

            </div>
        </div>*@

    </div>
<!--End of wrapper div-->

SpartanRooms10-31-19/Views/Home/TeghsAltView.cshtml
<style>
    .SpartanImage {
        background-image: url(https://www.rcm.it/wp-content/uploads/2019/09/pulire-scuola.jpg);
    }

    .SpartanLeftBackGroundColor {
        background-color: #f3cb7a;
    }

    .idk {
        background-repeat: no-repeat;
        background-size: 70%;
        background-position: right;
    }
</style>

<script>


</script>

@*
    <body>
        <form class="text-center border border-light p-5" style="position: relative; margin-left: 90vh;width: 400px;">

            <p class="h4 mb-4" style="color:white">Welcome To</p>
            <p style="margin-top: 5px;font-family:'Open Sans'; color:white; font-size: 35px"> Spartan Rooms</p>
            <p style="font-family:'High Tower Text'; color:white"> Reserve a Classroom!</p>
            <!-- Email -->
            <input type="email" id="defaultLoginFormEmail" class="form-control mb-4" placeholder="E-mail" style="border-radius: 35px">

            <!-- Password -->
            <input type="password" id="defaultLoginFormPassword" class="form-control mb-4" placeholder="Password" style="border-radius: 35px">

            <div class="d-flex justify-content-around">
                <div>
                    <!-- Remember me -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                        <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>
                    </div>
                </div>
            </div>

            <!-- Sign in button -->
            <button class="btn btn-info btn-block my-4" style="border-radius:35px" type="submit">Log in</button>

            <!-- Register -->
            <p>
                Not a member?
                <a href="">Register</a>
            </p>
        </form>
    </body>
*@
<div name="WrapperDiv" style="width:inherit; height:90vh">

    <div name="LoginContainer" class="col-md-2 col-md-10" style="width:30%; height:100%;background-color:#f3cb7a;float:left;padding:.3%;padding-top:10%;margin:0 auto; text-align:center;">
        <!--style="position: relative; margin-left: 90vh;width: 400px;"-->
        <form class="text-center p-5" style=" display:inline-block;">

            <p class="h4 mb-4" style="color:white;font-size:50px">Welcome To</p>
            <p style="margin-top: 5px;font-family:'Open Sans'; color:white; font-size:150px"> Spartan Rooms</p>
            <p style="font-family:'High Tower Text'; color:white; font-size:30px"> Reserve a Classroom!</p>
            <!-- Email -->
            <input type="email" id="defaultLoginFormEmail" class="form-control mb-4" placeholder="E-mail" style="border-radius: 35px">

            <!-- Password -->
            <input type="password" id="defaultLoginFormPassword" class="form-control mb-4" placeholder="Password" style="border-radius: 35px">

            <div class="d-flex justify-content-around">
                <div>
                    <!-- Remember me -->
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                        <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>
                    </div>
                </div>
            </div>

            <!-- Sign in button -->
            <button class="btn btn-info btn-block my-4" style="border-radius:15%" type="submit">Log in</button>

            <!-- Register -->
            <p>
                Not a member?
                <a href="">Register</a>
            </p>
        </form>
    </div>

    <div name="roomImageDiv" style="width:70%; height:100%;float:right;">
        <div style="width:100%; height:100%;background-repeat:no-repeat;background-image: url(https://www.rcm.it/wp-content/uploads/2019/09/pulire-scuola.jpg);background-size:cover;display:inline-block;background-position: center center">

        </div>
    </div>

</div>
<!--End of wrapper div-->